/*

-- Create Database/Schemas
*/


DROP DATABASE IF EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS bronze;
DROP DATABASE IF EXISTS silver;
CREATE DATABASE IF NOT EXISTS silver;
DROP DATABASE IF EXISTS gold;
CREATE SCHEMA IF NOT EXISTS gold;
USE bronze;
